// <auto-generated />
using Day08;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day08.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260212124208_addAllItialTables")]
    partial class addAllItialTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day08.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalesOfficeId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("SalesOfficeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            EmployeeName = "Emp1"
                        },
                        new
                        {
                            EmployeeId = 2,
                            EmployeeName = "Emp2"
                        },
                        new
                        {
                            EmployeeId = 3,
                            EmployeeName = "Emp3"
                        });
                });

            modelBuilder.Entity("Day08.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            OwnerId = 1,
                            OwnerName = "owner1"
                        },
                        new
                        {
                            OwnerId = 2,
                            OwnerName = "owner2"
                        });
                });

            modelBuilder.Entity("Day08.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalesOfficeId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PropertyId");

                    b.HasIndex("SalesOfficeId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            Address = "add1",
                            City = "city1",
                            SalesOfficeId = 1,
                            State = "stat1",
                            ZipCode = "zib1"
                        });
                });

            modelBuilder.Entity("Day08.SalesOffice", b =>
                {
                    b.Property<int>("OfficeNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficeNumber"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MangerId")
                        .HasColumnType("int");

                    b.HasKey("OfficeNumber");

                    b.HasIndex("MangerId")
                        .IsUnique();

                    b.ToTable("SalesOffices");

                    b.HasData(
                        new
                        {
                            OfficeNumber = 1,
                            Location = "loc1",
                            MangerId = 1
                        },
                        new
                        {
                            OfficeNumber = 2,
                            Location = "loc2",
                            MangerId = 2
                        },
                        new
                        {
                            OfficeNumber = 3,
                            Location = "loc3",
                            MangerId = 3
                        });
                });

            modelBuilder.Entity("Day08.Employee", b =>
                {
                    b.HasOne("Day08.SalesOffice", "SalesOffice")
                        .WithMany("Employees")
                        .HasForeignKey("SalesOfficeId");

                    b.Navigation("SalesOffice");
                });

            modelBuilder.Entity("Day08.Property", b =>
                {
                    b.HasOne("Day08.SalesOffice", "SalesOffice")
                        .WithMany("Properties")
                        .HasForeignKey("SalesOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOffice");
                });

            modelBuilder.Entity("Day08.SalesOffice", b =>
                {
                    b.HasOne("Day08.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("Day08.SalesOffice", "MangerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Day08.SalesOffice", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
